language: c
dist: trusty
sudo: required
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq make gcc-arm-none-eabi qemu-user

env:
  matrix:
  - OPTIMIZE_INTRINSICS=0
  - OPTIMIZE_INTRINSICS=1

script: make -f Makefile.gcc clean && make -f Makefile.gcc compute_ref.gccarm OPTIMIZE_INTRINSICS=${OPTIMIZE_INTRINSICS} && qemu-arm -cpu cortex-a9 compute_ref.gccarm && diff  stm-arm-neon.gccarm ref-rvct-neon-nofp16.txt

notifications:
  email:
    on_success: always
    recipients:
      - christophelyon@gmail.com
adb shell

pm uninstall -k –user 0 com.payjoy.access

pm uninstall -k –user 0 com.payjoy.permission
